### ISSUE TITLE
Date Object reference

### ISSUE THREAD

**Issue by nedavnij** [d3/d3-time#18]
The ranges function(timeMonts, timeDay) dont create new Date objects by floor, offset or ceil. It is the some object. In my use case I have a object there have 2 properties: 'from' and 'to'. I create a new Date Object with new Date(). A 'from' property  = d3.timeMonth.floor(date) and 'to' property = d3.timeDay.offset(from, -1). If I change a 'from' property, is a 'to' property as too changed(to==from). I think is the same object or reference in memory.

**Comment by mbostock** [comment]
Both [*interval*.from](https://github.com/d3/d3-time/blob/master/README.md#interval_from) and [*interval*.offset](https://github.com/d3/d3-time/blob/master/README.md#interval_offset) return new date objects, and neither modifies the input *date*.

```js
var date = new Date(2000, 0, 15); // 2000-01-15T08:00:00.000Z
var from = d3.timeMonth.floor(date); // 2000-01-01T08:00:00.000Z
var to = d3.timeMonth.offset(from, -1); // 1999-12-01T08:00:00.000Z
date; // 2000-01-15T08:00:00.000Z
from; // 2000-01-01T08:00:00.000Z
```

Note that two Date instances *a* and *b* representing the same moment in time are *not* considered equal according to JavaScript’s == and === operators because they are different objects. So:

```js
var a = new Date(2000, 0, 15);
var b = new Date(2000, 0, 15);
a == b; // false
a === b; // false
a < b; // false
a > b; // false
a >= b; // true
a <= b; // true
+a == +b; // true
+a === +b; // true
```

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
