### ISSUE TITLE
Release builded version inside bower package

### ISSUE THREAD

**Issue by evilaliv3** [d3/d3-time#20]
@mbostock: could you please provide the builded and minified file in the bower package?

this would be useful in order to be able to use the library in projects that uses bower instead of npm.

thanks!

**Comment by mbostock** [comment]
No. D3 supports [npm](https://npmjs.com) (see also [unpkg](https://unpkg.com)), [GitHub release attachments](https://github.com/d3/d3-time/releases) and [d3js.org](https://d3js.org/d3-time.v1.js). I will not support Bower because it requires storing generated files in git, which means managing dedicated git repositories for Bower (see my [mbostock-bower organization](https://github.com/mbostock-bower)), which is a giant pain. I strongly recommend using npm instead of Bower.
