### ISSUE TITLE
Hope to add timeQuarter

### ISSUE THREAD

**Issue by MrHeer** [d3/d3-time#39]
Hope to add `timeQuarter` and `timeQuarters`.
I think quarter interval is very important.

**Comment by curran** [comment]
What would be the expected behavior?

Note that fiscal quarters are defined differently for each country. See https://en.wikipedia.org/wiki/Fiscal_year

Should the `timeQuarter` function accept a country code as well?

Or, should it use the user's current locale?

It's an interesting proposal, but may be rather involved to implement and keep up to date.

**Comment by mbostock** [comment]
How would this be different than `d3.timeMonth.every(3)`?

**Comment by MrHeer** [comment]
> How would this be different than `d3.timeMonth.every(3)`?

For me, there are not different, thank you very much!
