### ISSUE TITLE
infinite loop on _interval_.filter

### ISSUE THREAD

**Issue by Fil** [d3/d3-time#57]
https://github.com/d3/d3-time/blob/main/src/interval.js#L40 will loop if the test is never true

for example: 

`d3.utcHour.filter((d) => false).range(0, 86400 * 1000) // 💣 infinite loop`

**Comment by mbostock** [comment]
I think the answer here is “don’t do that”. I don’t see what we could do differently since interval.range is built on interval.offset, and if interval.offset hangs because the filter never returns true, there’s no way to avoid the infinite loop. Also practically speaking, fixing this doesn’t seem urgent since people can write their custom intervals accordingly to avoid the infinite loop (and custom intervals aren’t very common).

**Comment by Fil** [comment]
yup, I was looking at the code and realized there's no easy way to prevent that from happening; you find it soon enough when you make the mistake ;-)
